import { expect, test } from '@playwright/test'
import { execFileSync } from 'node:child_process'

const origin = 'http://127.0.0.1:5173'
const conversationalId = process.env.LEAI_TEST_CONVERSATIONAL_SURVEY_ID
const likertId = process.env.LEAI_TEST_LIKERT_SURVEY_ID

async function acceptConsent(page: import('@playwright/test').Page) {
  const dialog = page.getByRole('dialog', { name: 'Before you begin' })
  await expect(dialog.getByRole('button', { name: 'Continue' })).toBeDisabled()
  await dialog.getByRole('checkbox', { name: /I have read and agree/i }).check()
  await dialog.getByRole('button', { name: 'Continue' }).click()
  await expect(dialog).toHaveCount(0)
}

test('the original consent choices and legal pages precede the student conversation', async ({ page }, testInfo) => {
  test.skip(!conversationalId, 'An isolated browser-test survey ID is required')
  await page.setViewportSize({ width: 1171, height: 682 })
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  const dialog = page.getByRole('dialog', { name: 'Before you begin' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Continue' })).toBeDisabled()
  await expect(page.getByRole('log', { name: 'Conversation' })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('original-consent-desktop.png') })
  const terms = await Promise.all([page.waitForEvent('popup'), dialog.getByRole('link', { name: 'Terms of Use' }).click()])
  await expect(terms[0].getByRole('heading', { name: 'LEAI Terms of Use' })).toBeVisible()
  await terms[0].close()
  const privacy = await Promise.all([page.waitForEvent('popup'), dialog.getByRole('link', { name: 'Privacy Policy' }).click()])
  await expect(privacy[0].getByRole('heading', { name: 'LEAI Privacy Policy' })).toBeVisible()
  await privacy[0].close()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(dialog.getByRole('button', { name: 'Continue' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.screenshot({ path: testInfo.outputPath('original-consent-mobile.png') })
  await dialog.getByRole('checkbox', { name: /I have read and agree/i }).check()
  await dialog.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('log', { name: 'Conversation' })).toBeVisible()
})

test('the old Save draft control downloads a real Word file with the saved answer', async ({ page }, testInfo) => {
  test.skip(!conversationalId, 'An isolated browser-test survey ID is required')
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  await expect(page.getByRole('button', { name: 'Save draft (.docx)' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message' }).fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText("I don't know")
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByRole('button', { name: 'Save draft (.docx)' }).click(),
  ])
  expect(download.suggestedFilename()).toMatch(/\.docx$/)
  const destination = testInfo.outputPath('saved-reflection.docx')
  await download.saveAs(destination)
  const xml = execFileSync('unzip', ['-p', destination, 'word/document.xml'], { encoding: 'utf8' })
  expect(xml).toContain('I don&apos;t know')
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Message' })).toBeEnabled()
  await page.getByRole('textbox', { name: 'Message' }).fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText('Do you think about what the AI is good and not so good at for the task you’re working on?')).toBeVisible()
})

test('conversational student cannot see Researcher-only debug state and restores the anonymous session', async ({ page }, testInfo) => {
  test.skip(!conversationalId, 'An isolated browser-test survey ID is required')
  await page.setViewportSize({ width: 1171, height: 682 })
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await expect(page.getByRole('heading', { name: 'Structured Reflection — conversational' })).toBeVisible()
  await acceptConsent(page)
  await expect(page.getByRole('log', { name: 'Conversation' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Message' })).toBeVisible()
  await expect(page.getByText('Do you think about what is the most appropriate information to give to the AI?')).toBeVisible()
  const firstAssistant = page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last()
  await expect(firstAssistant.getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('research-debug-hidden-for-student.png') })
  for (const width of [390, 820, 1022, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    if (width === 390) await page.screenshot({ path: testInfo.outputPath('research-debug-hidden-mobile.png') })
  }
  await page.setViewportSize({ width: 1171, height: 682 })
  await page.getByRole('textbox', { name: 'Message' }).fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText('Do you consider what information the AI needs to perform the task?')).toBeVisible()
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').first().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await page.reload()
  await expect(page.getByText('Do you consider what information the AI needs to perform the task?')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
})

test('Likert accepts a spoken-style rating through the regular text composer', async ({ page }) => {
  test.skip(!likertId, 'An isolated browser-test survey ID is required')
  test.setTimeout(90_000)
  await page.goto(`${origin}/feedback.html?id=${likertId}`)
  await expect(page.getByRole('heading', { name: 'Structured Reflection — rate and reflect' })).toBeVisible()
  await acceptConsent(page)
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('I think about how to give the most appropriate information to the AI.')
  await expect(page.getByRole('radio')).toHaveCount(0)
  await expect(page.getByRole('combobox')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Message' }).fill('I would say four.')
  const turnResponse = page.waitForResponse((response) => response.url().includes('/turns/') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send' }).click()
  const response = await turnResponse
  expect(response.request().postDataJSON()).toMatchObject({ kind: 'text', text: 'I would say four.' })
  expect(response.request().postDataJSON()).not.toHaveProperty('value')
  const payload = await response.json()
  expect(payload.results.P1.rating).toBe(4)
  expect(payload.prompt).toMatchObject({ item_id: 'P1' })
  expect(payload.results.P1.status).toBe('partial')
  expect(payload.messages.at(-1)).toMatchObject({ role: 'assistant' })
  expect(payload.messages.at(-1).content.trim().length).toBeGreaterThan(0)
  await page.getByRole('textbox', { name: 'Message' }).fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('I consider what information the AI needs to perform the task.')
})

test('an anonymous student can converse but cannot inspect Researcher-only debug state', async ({ page, browserName }, testInfo) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Run the real model turn once on the isolated local survey')
  await page.setViewportSize({ width: 1678, height: 970 })
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('Do you think about what is the most appropriate information to give to the AI?')
  await page.screenshot({ path: testInfo.outputPath('student-chat-initial.png'), fullPage: true })
  const message = page.getByRole('textbox', { name: 'Message' })
  await message.fill('For a class coding task, I give AI the task goal, the relevant code, and the error message. I leave out my classmates’ private information and passwords.')
  await message.press('Enter')
  await expect(page.getByRole('tooltip')).toContainText('Enter sends')
  await page.screenshot({ path: testInfo.outputPath('keyboard-send-hint.png') })
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('For a class coding task', { timeout: 60_000 })
  const activeAssistant = page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last()
  await expect(activeAssistant).toHaveClass(/student-assistant-arrival/)
  await expect(activeAssistant.getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('assistant-arrival-highlight.png') })
  await page.screenshot({ path: testInfo.outputPath('student-chat-debug-hidden.png'), fullPage: true })
  await page.reload()
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('For a class coding task')
  for (const width of [390, 820, 1022, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(page.getByRole('textbox', { name: 'Message' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
})

test('a live request for clarification gets an example without answering or advancing the question', async ({ page, browserName }, testInfo) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Run the real model turn once on the isolated local survey')
  test.setTimeout(90_000)
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  const message = page.getByRole('textbox', { name: 'Message' })
  await message.fill('What do you mean by that? Can you give me an example?')
  const turnResponse = page.waitForResponse((response) => response.url().includes('/turns/') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send' }).click()
  const payload = await (await turnResponse).json()
  expect(payload.prompt).toMatchObject({ item_id: 'P1', phase: 'answer' })
  expect(payload.progress_label).toContain('Question 1 of 4')
  expect(payload.answer_map.P1).toBeUndefined()
  const reply = payload.messages.at(-1).content as string
  expect(reply).not.toMatch(/\bP1\b|\bP2\b|\bM2\b/)
  expect(reply).toMatch(/for example|such as|like when/i)
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText(reply)
  await page.screenshot({ path: testInfo.outputPath('clarification-keeps-question-active.png'), fullPage: true })
})

test('an incomplete answer gets a follow-up in the same conversation before P2', async ({ page, browserName }) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Run the real model turn once on the isolated local survey')
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  await page.getByRole('textbox', { name: 'Message' }).fill('Yes.')
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText('Area 1 of 3 — Planning · Question 1 of 4').first()).toBeVisible({ timeout: 60_000 })
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('Yes.')
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Message' }).fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('Do you consider what information the AI needs to perform the task?')
})

test('a Likert rating and real written explanation are recorded together', async ({ page, browserName }) => {
  test.skip(!likertId || browserName !== 'chromium', 'Run the real model turn once on the isolated local survey')
  test.setTimeout(90_000)
  await page.goto(`${origin}/feedback.html?id=${likertId}`)
  await acceptConsent(page)
  const text = 'I would say four, because I decide what task context and examples to share, while leaving out private information.'
  await expect(page.getByRole('radio')).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Message' }).fill(text)
  const turnResponse = page.waitForResponse((response) => response.url().includes('/turns/') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Send' }).click()
  const response = await turnResponse
  expect(response.request().postDataJSON()).toMatchObject({ kind: 'text', text })
  expect(response.request().postDataJSON()).not.toHaveProperty('value')
  const payload = await response.json()
  expect(payload.results.P1.rating).toBe(4)
  const studentMessages = payload.messages.filter((message: { role: string; content: string }) => message.role === 'student' && message.content === text)
  expect(studentMessages).toHaveLength(1)
  expect(payload.answer_map.P1).toContain(studentMessages[0].sequence)
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText(text, { timeout: 60_000 })
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  const restoredResponse = page.waitForResponse((response) => /\/sessions\/[^/]+\/$/.test(new URL(response.url()).pathname) && response.request().method() === 'GET')
  await page.reload()
  const restored = await (await restoredResponse).json()
  expect(restored.results.P1.rating).toBe(4)
  expect(restored.answer_map.P1).toContain(studentMessages[0].sequence)
  await expect(page.getByRole('log', { name: 'Conversation' }).getByText(text, { exact: true })).toHaveCount(1)
})

test('all-question completion stays editable, a real correction remaps P1, and final download freezes it', async ({ page, browserName }, testInfo) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Use one isolated live-model browser run')
  test.setTimeout(120_000)
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  const message = page.getByRole('textbox', { name: 'Message' })
  for (let index = 0; index < 11; index += 1) {
    await message.fill("I don't know")
    await page.getByRole('button', { name: 'Send' }).click()
    await expect(page.getByRole('log', { name: 'Conversation' }).getByText("I don't know", { exact: true })).toHaveCount(index + 1)
  }
  await expect(page.getByText(/All questions are captured/)).toBeVisible()
  await expect(message).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('questions-complete-still-editable.png'), fullPage: true })
  await message.fill('Actually, change my P1 answer: I remove private details before giving the AI my task goal and relevant code.')
  await page.getByRole('button', { name: 'Send' }).click()
  const revisionReply = page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last()
  await expect(revisionReply).toContainText('updated your response to', { timeout: 60_000 })
  await expect(revisionReply).not.toContainText(/\bP1\b|\bM2\b/)
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('p1-revision-mapped.png'), fullPage: true })
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.getByRole('button', { name: 'Download my reflection (Word / .docx)' }).click(),
  ])
  expect(download.suggestedFilename()).toMatch(/-final\.docx$/)
  const destination = testInfo.outputPath('final-mapped-reflection.docx')
  await download.saveAs(destination)
  const xml = execFileSync('unzip', ['-p', destination, 'word/document.xml'], { encoding: 'utf8' })
  expect(xml).toContain('private details')
  await expect(page.getByText('Reflection downloaded. This version is final.')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Message' })).toHaveCount(0)
})

test('a live correction to P1 while P2 is current updates P1 without skipping P2', async ({ page, browserName }, testInfo) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Use one isolated live-model browser run')
  test.setTimeout(90_000)
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  const message = page.getByRole('textbox', { name: 'Message' })
  await message.fill("I don't know")
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByText('Do you consider what information the AI needs to perform the task?')).toBeVisible()
  await message.fill('Actually, change my P1 answer: I give AI my task goal and code while leaving out passwords and private student details.')
  await page.getByRole('button', { name: 'Send' }).click()
  const revisionReply = page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last()
  await expect(revisionReply).toContainText('updated your response to', { timeout: 60_000 })
  await expect(revisionReply).not.toContainText(/\bP1\b|\bM2\b/)
  await expect(page.getByRole('textbox', { name: 'Message' })).toBeEnabled()
  await expect(page.getByRole('log', { name: 'Conversation' }).locator('[data-chat-role="assistant"]').last().getByRole('button', { name: /debug state/i })).toHaveCount(0)
  await expect(page.locator('.student-progress').getByText('Area 1 of 3 — Planning · Question 2 of 4')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('earlier-p1-correction-during-p2.png'), fullPage: true })
})

test('header and reflection strip auto-collapse after the first answer and reveal on hover or touch', async ({ page, browser, browserName }, testInfo) => {
  test.skip(!conversationalId || browserName !== 'chromium', 'Use an isolated synthetic local survey and Chromium')
  test.setTimeout(120_000)
  await page.setViewportSize({ width: 1171, height: 820 })
  await page.goto(`${origin}/feedback.html?id=${conversationalId}`)
  await acceptConsent(page)
  const header = page.locator('#student-chat-header')
  const downloads = page.locator('#reflection-downloads')
  const composer = page.getByTestId('chat-composer')
  const composerInput = composer.getByRole('textbox', { name: 'Message' })
  await expect(composerInput).toHaveCSS('border-top-width', '0px')
  await expect(composer).toHaveCSS('border-radius', '26px')
  await expect(composer.getByRole('button', { name: 'Send' })).toHaveCount(1)
  await expect(composer.getByRole('button', { name: 'Dictate' })).toHaveCount(1)
  await expect(composer.getByRole('button', { name: /add|attach/i })).toHaveCount(0)
  await expect(header).toHaveAttribute('aria-hidden', 'false')
  await expect(downloads).toHaveAttribute('aria-hidden', 'false')
  const message = page.getByRole('textbox', { name: 'Message' })
  await message.fill('I choose information based on the task goal and what the AI needs; I share relevant code but remove private details and passwords.')
  const sendButton = composer.getByRole('button', { name: 'Send' })
  const micButton = composer.getByRole('button', { name: 'Dictate' })
  await expect(sendButton).toBeEnabled()
  await expect(sendButton).toHaveCSS('background-color', 'rgb(0, 100, 147)')
  await expect(micButton).toHaveCSS('background-color', 'rgb(0, 100, 147)')
  await expect(sendButton).toHaveCSS('opacity', '1')
  await page.screenshot({ path: testInfo.outputPath('chat-composer-ready-to-send.png') })
  await page.getByRole('button', { name: 'Send' }).click()
  await expect(page.getByRole('log', { name: 'Conversation' })).toContainText('I choose information based on the task goal', { timeout: 60_000 })
  await expect(header).toHaveAttribute('aria-hidden', 'true')
  await expect(downloads).toHaveAttribute('aria-hidden', 'true')
  for (const width of [390, 820, 1022, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
  await page.setViewportSize({ width: 1171, height: 820 })
  await page.screenshot({ path: testInfo.outputPath('chrome-auto-collapsed-desktop.png'), fullPage: true })

  await page.mouse.move(160, 4)
  await expect(header).toHaveAttribute('aria-hidden', 'false')
  await expect(header).toHaveCSS('opacity', '1')
  await page.screenshot({ path: testInfo.outputPath('header-revealed-on-hover.png'), fullPage: true })
  await page.mouse.move(580, 280)
  await expect(header).toHaveAttribute('aria-hidden', 'true')

  const downloadRegion = page.getByTestId('student-download-region')
  const downloadBox = await downloadRegion.boundingBox()
  expect(downloadBox).not.toBeNull()
  await page.mouse.move(downloadBox!.x + downloadBox!.width / 2, downloadBox!.y + 4)
  await expect(downloads).toHaveAttribute('aria-hidden', 'false')
  await expect(downloads.getByText('Reflection in progress')).toBeVisible()
  await expect(downloads).toHaveCSS('opacity', '1')
  await page.screenshot({ path: testInfo.outputPath('reflection-strip-revealed-on-hover.png'), fullPage: true })
  await page.locator('#reflection-downloads-toggle').click()
  await expect(page.locator('#reflection-downloads-toggle')).toHaveAttribute('aria-pressed', 'true')
  await page.mouse.move(580, 280)
  await expect(downloads).toHaveAttribute('aria-hidden', 'false')
  await page.locator('#reflection-downloads-toggle').click()
  await page.mouse.move(580, 280)
  await expect(downloads).toHaveAttribute('aria-hidden', 'true')

  const touchContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  try {
    const touchPage = await touchContext.newPage()
    await touchPage.goto(`${origin}/feedback.html?id=${conversationalId}`)
    await acceptConsent(touchPage)
    const touchMessage = touchPage.getByRole('textbox', { name: 'Message' })
    await touchMessage.fill('I provide the goal and relevant context while leaving out private information.')
    await touchPage.getByRole('button', { name: 'Send' }).click()
    await expect(touchPage.getByRole('log', { name: 'Conversation' })).toContainText('I provide the goal and relevant context', { timeout: 60_000 })
    await expect(touchPage.locator('#student-chat-header')).toHaveAttribute('aria-hidden', 'true')
    await touchPage.screenshot({ path: testInfo.outputPath('chrome-auto-collapsed-mobile.png'), fullPage: true })
    await touchPage.locator('.student-header-toggle').tap()
    await expect(touchPage.locator('#student-chat-header')).toHaveAttribute('aria-hidden', 'false')
    await expect(touchPage.locator('#student-chat-header')).toHaveCSS('opacity', '1')
    await touchPage.locator('#reflection-downloads-toggle').tap()
    await expect(touchPage.locator('#reflection-downloads')).toHaveAttribute('aria-hidden', 'false')
    await expect(touchPage.locator('#reflection-downloads')).toHaveCSS('opacity', '1')
    expect(await touchPage.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await touchPage.screenshot({ path: testInfo.outputPath('chrome-revealed-mobile.png'), fullPage: true })
  } finally {
    await touchContext.close()
  }
})
